### PR TITLE
Http exception

### PR DESCRIPTION
**Pull request by eerwitt**
Added in a few items which were useful and want to see what you think.
- Added in a local debugger, it's quite useful with node programs.
- Changes to support returning a 404 error message (used in module-02).
- Created a function to return singular resources (if this is useful we can change it to a promise).

### CODE REVIEW

**Comment by cameronjacoby** [comment]
:+1: to all your changes. Love the helper function for handling singular responses and the added 404 error-handling. A few things I just added on:
- Formatted all errors to come back as objects with the key `error`
- Changed `GET /books` and `GET /wines` to return objects

**Comment by cameronjacoby** [comment]
```
res.json(foundObject);
    ^
ReferenceError: res is not defined
```

**Comment by cameronjacoby** [comment]
@eerwitt Looks like the response is not available in our `getSingularResponse` function. Not exactly sure how to fix it. Is this what you mean by refactoring to a promise instead?

**Comment by eerwitt** [comment]
@cameron nope, just an error in my code as I forgot to wrap the response object.

**Comment by eerwitt** [comment]
@cameronjacoby _should_ be fixed, I didn't add any tests this time but will next time. Which testing framework are we planning to teach? I saw `mocha` but wasn't sure.

**Comment by cameronjacoby** [comment]
Awesome, thanks! Just tested it out, and it's working for me.

We should write tests... at some point.

We usually teach `mocha`/`chai` and we added in `request` in 19/20 and only showed them request specs for the Express API. I'm open to using something different if there's something else you'd recommend. I do think we should keep testing fairly simple through. Having one test per API route is plenty at this stage just to get the feel of testing.

**Pull request merged**
